### ISSUE TITLE
Making beginner friendly Issues

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#1]
Issues related to DSA, CP, JS, HTML+CSS, operating system

Start with 6 Issues per DSA - 2x{Easy, Medium, Hard} :
-   Arrays
-   Stacks
-   Queues & priority queue
-   Linked List
-   Hashmap
-   Trees
-   Recursion
-   Dynamic Programming
-   Graphs
-   General algorithm

**Comment by Gauravsharma-20** [comment]
Arrays Done.

**Comment by ultimatecoder2** [comment]
Stacks Done

**Comment by Gauravsharma-20** [comment]
Hashmaps Done

**Comment by ultimatecoder2** [comment]
Queues & priority queue done

**Comment by ultimatecoder2** [comment]
Linked List done

**Comment by tejvirus0003** [comment]
recusion done ///
