### ISSUE TITLE
Maximum Tiles Cleaned by a robot in a 2D matrix

### ISSUE THREAD

**Issue by Vibhu1710** [PEC-CSS/Open-Source#130]
## Maximum Tiles cleaned by a robot in a 2D matrix
Given a 2D matrix of m rows and n columns. A cleaner robot is placed at  position (0,0). The robot moves in the forward direction cleaning the tiles ('.') until an obstacle ('#') or the border of the matrix is encountered. It then turns around in clockwise direction and moves forward until another obstacle is encountered. Following the above rules, the robot forms a cleaning path for itself. Output the maximum number of tiles the robot can clean for a given matrix.

Constraints:
- arr[i][j]=='#' || arr[i][j] =='.' 
- 1<=m<=20, 1<=n<=20
-  The starting point will always be a tile ('.')

### Example case 1:
Input string : {"...#","....","#...","..#.","...."}
Output: 7
![Capture_2d](https://user-images.githubusercontent.com/66901877/135716582-3cbe0cd0-4db6-43b1-bb3e-65df9f1c76f2.PNG)
 
### Example case 2:
Input string : {"...#...#..","..........",".#...#.#..","..........","......#...","#..#......"}
Output: 36
![Capture_2d2](https://user-images.githubusercontent.com/66901877/135717324-5018c12f-aeb6-4819-8b45-6d15b9dcbd64.PNG)

**Comment by Vibhu1710** [comment]
Has been solved once...Other approaches to the question are welcome !

**Comment by Dhruv-IGI** [comment]
Can you assign me this issue for hacktuber fest

**Comment by Vibhu1710** [comment]
Done.
