### ISSUE TITLE
Implementing Hashmap

### ISSUE THREAD

**Issue by ultimatecoder2** [PEC-CSS/Open-Source#142]
Implement your own hashmap, without using library function (of hashmap). 
Design such hash function, that can have less probability of collision

**Comment by dhananjay8968** [comment]
What are the constraints on (key, value) pair?

**Comment by ultimatecoder2** [comment]
You can assume that key will be a string and value can be any valid integer. 

We just want to focus more on the method being used to implement this data-structure.  So you can make some necessary assumptions if you want. It will be good if you can write down those assumptions in your code file also (if you make any).

You can also mention the time and space complexity of your solution in code file itself.
