### ISSUE TITLE
Implement KMP algorithm

### ISSUE THREAD

**Issue by ultimatecoder2** [PEC-CSS/Open-Source#143]
Implement KMP (Knuth–Morris–Pratt) algorithm

## Input:
2 strings 'text' and 'pattern'

## Output:
 If pattern is found, print the starting index of matching pattern in string text. In case of multiple matches, just print the smallest possible answer.
If pattern doesn't matches any substring of text, then print -1;

## Sample test case
text = "THIS IS A TEST TEXT"
pattern = "TEST"
Output: 10

**Comment by M-Manas-s** [comment]
Hey, I cannot clone the forked repo because "Good-First-Issues/#include <bits" is an invalid name.
