### ISSUE TITLE
0-1 Knapsack Problem

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#146]
Given weights and values of n items, put these items in a knapsack of capacity W to get the maximum total value in the knapsack. In other words, given two integer arrays val[0..n-1] and wt[0..n-1] which represent values and weights associated with n items respectively. Also given an integer W which represents knapsack capacity, find out the maximum value subset of val[] such that sum of the weights of this subset is smaller than or equal to W. You cannot break an item, either pick the complete item or don’t pick it (0-1 property).

![](https://media.geeksforgeeks.org/wp-content/cdn-uploads/knapsack-problem.png)

**Comment by siddharth1704** [comment]
Can you assign me this issue

**Comment by Deepchavan1** [comment]
@Gauravsharma-20 can you please assign this to me?

**Comment by Gauravsharma-20** [comment]
@Deepchavan1 can you look for another issue

**Comment by Deepchavan1** [comment]
@Gauravsharma-20 yes sure, np!

**Comment by siddharth1704** [comment]
@Gauravsharma-20  can you check the PR #180  I have  generated
