### ISSUE TITLE
Intro-sort

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#206]
Write in detail about Intro-Sort algoirthm and pseudo code of your implementation.

**Comment by Ruchika-20** [comment]
Hello Sir...please assign me this issue , I would like to work on it . I will provide C++ implementation of intro-sort algorithm along with other necessary information

**Comment by Ruchika-20** [comment]
hey I have created intro sort file please give path of the directory where I add it.
@Gauravsharma-20

**Comment by Ruchika-20** [comment]
I've created the PR...kindly have a look @Gauravsharma-20
