### ISSUE TITLE
Implement Kosaraju Algorithm for finding SCC

### ISSUE THREAD

**Issue by ultimatecoder2** [PEC-CSS/Open-Source#211]
Implement Kosaraju Algorithm for finding Strongly Connected Components for a **directed graph**. 
Graph has **n nodes, numbered from 0 to n-1**. You need to print each strongly connected component in new line.

_Strongly Connected Components: -_ In directed graphs, a graph is said to be strongly connected if every vertex is reachable from every other vertex. The strongly connected components of an arbitrary directed graph form a partition into subgraphs that are themselves strongly connected.

## Input Format:
1st line contains an integer n, denoting number of nodes present in graph. Next n lines will contain 2 integers denoting From vertex  and to vertex

## Output format:
Print all SCC's. Each new SCC should be printed in different line.

### Sample Input1
5
0 2
2 1
1 0
0 3
3 4

### Sample Output 1
0 1 2
3
4

![SCC](https://user-images.githubusercontent.com/43994883/136318473-11c351d7-4b3a-436d-9683-d7879cbfc969.png)

**Comment by gargi-agrawal** [comment]
Can I work on this issue?
