### ISSUE TITLE
Check AB

### ISSUE THREAD

**Issue by Aaryan8751** [PEC-CSS/Open-Source#213]
Suppose you have a string, S, made up of only 'a's and 'b's. Write a recursive function that checks if the string was generated using the following rules:

a. The string begins with an 'a'
b. Each 'a' is followed by nothing or an 'a' or "bb"
c. Each "bb" is followed by nothing or an 'a'

If all the rules are followed by the given string, return true otherwise return false.

Input format :
String S
Output format :
'true' or 'false'

Constraints :
1 <= |S| <= 1000
where |S| represents length of string S.

Sample Input 1 :
abb
Sample Output 1 :
true

Sample Input 2 :
abababa
Sample Output 2 :
false

**Comment by nishantkantojha** [comment]
Hi @Aaryan8751, I want to contribute my solution to this particular Pull Request.
Can you assign the PR to me ☺️

**Comment by Gauravsharma-20** [comment]
@nishantkantojha PR for this has already been raised, can you look for another issue

**Comment by diwakar1998** [comment]
is this problem solvable using regex?i would like to try and submit my solution

**Comment by Aaryan8751** [comment]
@diwakar1998 yes it is valid
