### ISSUE TITLE
Pascal Triangle Row

### ISSUE THREAD

**Issue by ultimatecoder2** [PEC-CSS/Open-Source#214]
Given an integer rowIndex, return the rowIndexth (0-indexed) row of the Pascal's triangle.

In Pascal's triangle, each number is the sum of the two numbers directly above it as shown:
![PascalTriangleAnimated2](https://user-images.githubusercontent.com/43994883/136429298-7c0a51f5-7b15-44ba-b510-61426f106430.gif)

## Sample Test Case 1
Input: rowIndex = 3
Output: [1,3,3,1]

## Sample Test Case 2
Input: rowIndex = 1
Output: [1,1]

**Comment by Catunoo** [comment]
Can you please assign this issue to me
