### ISSUE TITLE
Rectangular numbers

### ISSUE THREAD

**Issue by Aaryan8751** [PEC-CSS/Open-Source#232]
Print the following pattern for the given number of rows.
Pattern for N = 4
4444444
4333334
4322234
4321234
4322234
4333334  
4444444
Input format : N (Total no. of rows)

Output format : Pattern in N lines

Sample Input :
3
Sample Output :
33333
32223
32123
32223
33333

**Comment by Abhishek-Greninja17** [comment]
I would like to work on this issue if it isn't assigned to anyone else

**Comment by Abhishek-Greninja17** [comment]
I have completed the following issue #232 #234 of Rectangular Number, Please have a look on my PR
