### ISSUE TITLE
Maximum rectangular area of Histogram

### ISSUE THREAD

**Issue by ultimatecoder2** [PEC-CSS/Open-Source#25]
Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.

## Input
First line contains an integer n, denoting the size of array.
Next n lines will contain elements of array

## Output
A single integer, denoting the maximum possible area of rectangle that can be made from the histogram

### Sample Input 1
6
2 1 5 6 2 3

### Sample Output 1
10

### Explaination
![histogram](https://user-images.githubusercontent.com/43994883/133650212-ee94a63e-e23e-4177-a214-187242a1fb04.jpg)

## Expected Complexities
Space Complexity - O(n)
Time Complexity - O(n)

**Comment by akash-rao-2001** [comment]
hey i am a beginner.. could u assign me this problem
