### ISSUE TITLE
Pattern Matching with Tries

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#277]
Given a list of n words and a pattern p that we want to search. Check if the pattern p is present the given words or not. Return true if the pattern is present and false otherwise.

Input Format :
The first line of input contains an integer, that denotes the value of n.
The following line contains n space separated words.
The following line contains a string, that denotes the value of the pattern p.

Output Format :
The first and only line of output contains true if the pattern is present and false otherwise.

**Implement Using Tries Data Structure.**

```
Sample Input:
4
abc def ghi cba
de

Sample Output:
true
```

**Comment by VishalAmbavade** [comment]
Hi @Gauravsharma-20, can you assign me this issue?

**Comment by Gauravsharma-20** [comment]
Sure.

**Comment by Gauravsharma-20** [comment]
In good-first-issue folder
