### ISSUE TITLE
Find elements of original array from doubled array

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#293]
Given an array arr[] of 2*N integers such that it consists of all elements along with the twice values of another array, say A[], the task is to find the array A[].

Example:
Input: arr[] = {4, 1, 18, 2, 9, 8}
Output: 1 4 9
Explanation:
After taking double values of 1, 4, and 9 then adding them to the original array, All elements of the given array arr[] are obtained 

Input: arr[] = {4, 1, 2, 2, 8, 2, 4, 4}
Output: 1 2 2 4

**Comment by AndrasBard** [comment]
Would you like to assign this issue to me?

**Comment by Meghwantsingh** [comment]
Hello , I also like to work on this problem.
