### ISSUE TITLE
Merge Two Sorted Lists

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#318]
Merge two sorted linked lists and return it as a sorted list. The list should be made by splicing together the nodes of the first two lists.

![](https://assets.leetcode.com/uploads/2020/10/03/merge_ex1.jpg)

```
Example 1:

Input: l1 = [1,2,4], l2 = [1,3,4]
Output: [1,1,2,3,4,4]
Example 2:

Input: l1 = [], l2 = []
Output: []
Example 3:

Input: l1 = [], l2 = [0]
Output: [0]
```

**Comment by Samiya-Nisar** [comment]
Sir, can you please assign me this task!!
