### ISSUE TITLE
Longest Duplicate Substring

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#334]
Given a string s, consider all duplicated substrings: (contiguous) substrings of s that occur 2 or more times. The occurrences may overlap.

Return any duplicated substring that has the longest possible length. If s does not have a duplicated substring, the answer is "".

```
Examples:

Input: s = "banana"
Output: "ana"

Input: s = "abcd"
Output: ""
```
 

Constraints:
2 <= s.length <= 3 * 104
s consists of lowercase English letters.

**Comment by darshan4416** [comment]
I would like to work on this. Please assign it to me.
