### ISSUE TITLE
Queue Implementation using Linked List

### ISSUE THREAD

**Issue by ultimatecoder2** [PEC-CSS/Open-Source#39]
Implement a queue data-structure using Linked List
Your should implement the following functions:
1) enqueue (int x) // Insert an element to queue
2) deque() //removes an element from queue
3) size() //returns the number of elements present in the queue

### Time Complexity
enqueue - O(1)
deque - O(1)
size - O(1)

**Comment by yellowHatpro** [comment]
Is it necessary to use int data type for elements? 
Or can we also use templates instead?
