### ISSUE TITLE
Generate binary numbers between '1 to n' using a queue

### ISSUE THREAD

**Issue by ultimatecoder2** [PEC-CSS/Open-Source#41]
Given a positive number 'n', efficiently generate binary numbers between 1 and n using the queue data-structure in linear time.

## Input 
You are given an integer n (n>0)

## Output
An array containing n elements, representing binary representation of integers from 1 to n

###  Sample Input 1
16
### Sample Output 1
1 10 11 100 101 110 111 1000 1001 1010 1011 1100 1101 1110 1111 10000

**Comment by Auleen** [comment]
In the given problem statement, the input is given to be 10, however, the output shows the binary representations for all numbers from 1 to 16.

**Comment by ultimatecoder2** [comment]
@Auleen thanks for correction
