### ISSUE TITLE
WorD b r E a  k (word - break problem)

### ISSUE THREAD

**Issue by tejvirus0003** [PEC-CSS/Open-Source#51]
Given a  string and set of words (strings) , determine ,how many and which words can be segmented out by separating the string by spaces , like for example
set : { this, th, is, famous, Word, break, b, r, e, a, k, br, bre, brea, ak, problem }
string : Wordbreakproblem
output : 
Word , break , b , r , e , a , k , br , bre , brea , ak , problem
no of words : 11
solve this question in minumum time and space, if u can ...

hint : ( recursion (good) , or dynamic programming )

**Comment by M-Manas-s** [comment]
Hi! The test case has 12 words in the output :)
