### ISSUE TITLE
Staircase

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#57]
A child is running up a staircase with N steps, and can hop either 1 step, 2 steps or 3 steps at a time. Implement a method to count how many possible ways the child can run up to the stairs. You need to return number of possible ways W.

Sample Input : 4
Sample Output: 7

Explanation (contributed by @satvikDesktop) :
1. 1,1,1,1
2. 2,1,1
3. 1,2,1
4. 1,1,2
5. 3,1
6. 1,3
7. 2,2

**Comment by ariisraeli** [comment]
Sorry for the question, but how is the output of 4 is 7?
1) 1.1.1.1
2) 2,1,1
3) 1,2,1
4) 1,1,2
5) 3,1
6) 1,3

**Comment by satvikDesktop** [comment]
> 1) 1.1.1.1
> 2) 2,1,1
> 3) 1,2,1
> 4) 1,1,2
> 5) 3,1
> 6) 1,3
> 7) 2,2

**Comment by Gauravsharma-20** [comment]
It's okay, comments are encouraged especially for anything regarding the issue. exactly what @satvikDesktop mentioned

**Comment by satvikDesktop** [comment]
> It's okay, comments are encouraged especially for anything regarding the issue. exactly what @satvikDesktop mentioned

I'm sorry I thought I would let you answer 😂

**Comment by satvikDesktop** [comment]
> Sorry for the question, but how is the output of 4 is 7?
> 1) 1.1.1.1
> 2) 2,1,1
> 3) 1,2,1
> 4) 1,1,2
> 5) 3,1
> 6) 1,3

The last is 2,2
