### ISSUE TITLE
Reverse a String 

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#6]
You are given a string s. You need to reverse the string.

You only need to complete the function reverseWord() that takes `s` as parameter and returns the reversed string.

Expected Time Complexity: O(|S|).
Expected Auxiliary Space: O(1).

Input: s = string
Output: gnirts

**Comment by Nabhag8848** [comment]
Hey,I Would like to Add this.....Can to Assign it to me.....
