### ISSUE TITLE
Median of Two Sorted Arrays

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#8]
Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

The overall run time complexity should be O(log (m+n)).

Input: nums1 = [1,3], nums2 = [2]
Output: 2.00000

Explanation: merged array = [1,2,3] and median is 2.

**Comment by RaashiAgarwal** [comment]
where should i add this code?

**Comment by Gauravsharma-20** [comment]
Please create a pull request and name the file `Median_of_Two_Sorted_Arrays.cpp` inside the Good-First-Issues folder

Here's how you can create a pull request:
- https://www.youtube.com/watch?v=LuL60r-XnL4​
- https://www.youtube.com/watch?v=rgbCcBNZcdQ​
