### ISSUE TITLE
Sliding Window Maximum

### ISSUE THREAD

**Issue by Gauravsharma-20** [PEC-CSS/Open-Source#9]
You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position.

Return the max sliding window (vector).

Input: nums = [1,3,-1,-3,5,3,6,7], k = 3
Output: [3,3,5,5,6,7]

Explanation: 
Window position                Max
---------------               -----
[1  3  -1] -3  5  3  6  7       3
 1 [3  -1  -3] 5  3  6  7       3
 1  3 [-1  -3  5] 3  6  7       5
 1  3  -1 [-3  5  3] 6  7       5
 1  3  -1  -3 [5  3  6] 7       6
 1  3  -1  -3  5 [3  6  7]      7

**Comment by Arjun31415** [comment]
I'm sorry but I do not understand the output. How do you have 6 numbers in the output sliding window when there are only maximum 3 (k=3) elements in the window.
Also how do you compare two sliding windows ? Lexicographical or sum or maximum element in the window?

**Comment by Gauravsharma-20** [comment]
As shown in the explanation, the window of K (here 3) keeps moving across the array, in the first case the maximum in that window of k is the value 3 ([1 3 -1]). then the window moves forward by one and the maximum in that window is 3 ([3 -1 3]) and so on. So the final output array will be of length (N-K+1) and in each window you have to check for the maximum integer.

**Comment by Arjun31415** [comment]
Oh i understand. Thank you for the explanation
